
LET CR_ID = '126787';
PROC IMPORT OUT = RMINPUT.&CR_ID._INPUT1
    DATAFILE= "/sasapp/Ccode/ds5/datamasterinput1.xlsx"
    DBMS=XLSX Replace;
    OPTIONS VALIDVARNAME=v7 MSGLEVEL=I;
 RUN;
 
 PROC IMPORT OUT = RMINPUT.&CR_ID._INPUT2
    DATAFILE= "/sasapp/Ccode/ds5/datamasterinput2.xlsx"
    DBMS=XLSX Replace;
    OPTIONS VALIDVARNAME=v7 MSGLEVEL=I;
 RUN;
 
/*  COMBINE DATA */
 PROC SQL;
 CREATE TABLE REMINPUT.&CR_ID._INPUT
  A.ACCT_NUM
 ,B.LOAN_ID
 ,B.IMPACT_START_DT
 ,B.IMPACT_END_DT
 ,A.REPO_DT
 ,A.EXCL_STEP
 FROM (SELECT
   LOANACCTNUMBER as LOAN_ACCT_NBR
   MINERDATE as IMPACT_START_DT FORMAT=MMDDYY10.
   IMPACTENDDATE as IMPACT_END_DT FORMAT=MMDDYY10.
   REPODATE AS REPO
   '1639099' as REMED_CR
   FROM RMINPUT.&CR_ID._INPUT1
   WHERE LOAN_ACCT_NBR NE .
   UNION ALL
   SELECT
   LOANACCTNUMBER as LOAN_ACCT_NBR
   MINERDATE as IMPACT_START_DT FORMAT=MMDDYY10.
   IMPACTENDDATE as IMPACT_END_DT FORMAT=MMDDYY10.
   REPODATE AS REPO
   '1639099' as REMED_CR
   FROM RMINPUT.&CR_ID._INPUT2
   ) A
   LEFT JOIN DW_DW_LOAN_VER_2 
   ON A.LOAN_ACCT_NBR = B.LOAN_ACCT_NBR
   ORDER BY A.REMED_CR, A.LOAN_ACCT_NBR;
   QUIT;
   
 