LET CR_ID = '126777';
PROC IMPORT OUT = RMINPUT.&CR_ID._INPUTFILE_1
    DATAFILE= "/sasapp/Ccode/dss5/datamasterinput1.xlsx"
    DBMS=XLSX Replace;
    OPTIONS VALIDVARNAME=v7 MSGLEVEL=I;
 RUN;
 
 PROC SQL;
 CREATE TABLE REQ2.EXTRACT_DATASET
 SELECT
 A.LOAN_NUM
 ,A.FIRST_NAME
 ,A.ALT_STATE
 ,A.ALT_CITY
 ,A.A.TOTAL_AMT
 ,A.LOAN_PAYAMT
 ,A.CUST_SATIS_NUM
 ,B.CFK_TAX_ID
 ,CASE WHEN (B.CFK_TAX_ID) IS NOT NUMM THEN
    CASE WHEN LEMGTH (B.CFK_TAX_ID) ne 9 THEN ''
         WHEN NOTDIGIT(TRIM(B.CFK_TAX_ID)) > 0 THEN ''
         WHEN (B.CFK_TAX_ID) in ('111111111', '222222222') THEN ''
         ELSE (B.CFK_TAX_ID)  END     
  ELSE '' END AS CFK_INVALID
 ,CASE WHEN A.ALT_CITY NE '?' THEN UPCASE (A.ALT_CITY) ELSE (B.CITY)
   END AS CITY
 FROM 126777_INPUTFILE_1
 RIGHT JOIN datamasterinput2
  ON A.LOAN_NUM =B.LOAN_NUM;
 QUIT;
 
  
  
  
  